name: cyberbracy_mpt_original_front
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_svg: ^2.0.6
  flutter_bloc:
  dio:
  flutter_pretty_dio_logger:
  get_it:
  pretty_dio_logger:
  pinput:
  intl:
  equatable:
  dartz:
  flutter_staggered_animations:
  html:
  flutter_markdown:
  url_launcher:
  
  flutter_secure_storage: ^8.0.0
  flutter_native_splash: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter_native_splash:
  color: '#ffffff'
  image: 'assets/logo.png'
  android_12:
    color: '#ffffff'

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: CustomIcon
      fonts:
        - asset: fonts/CustomIcon.ttf

